pure_pursuit_multi_node:
  ros__parameters:
    # --- Global Settings (2 spaces) ---
    odom_topic: "/pf/pose/odom"
    car_refFrame: "laser"
    global_refFrame: "map"
    drive_topic: "/drive"
    rviz_waypointselected_topic: "/waypoint_selected"
    steering_limit: 25.0
  
    # --- Inner Line (0) ---
    inner:
      waypoints_path: "/home/f1tenth/f1tenth_auto_blocking/lab_ws25/src/pure_pursuit/racelines/Raceline_inside.csv"
      min_lookahead: 1.0
      max_lookahead: 3.0
      lookahead_ratio: 8.0
      K_p: 0.2
      velocity_percentage: 0.5

    # --- Middle Line (1) ---
    middle:
      waypoints_path: "/home/f1tenth/f1tenth_auto_blocking/lab_ws25/src/pure_pursuit/racelines/Raceline_middle.csv"
      min_lookahead: 1.0
      max_lookahead: 3.0
      lookahead_ratio: 8.0
      K_p: 0.2
      velocity_percentage: 0.5
      
    # --- Outer Line (2) ---
    outer:
      waypoints_path: "/home/f1tenth/f1tenth_auto_blocking/lab_ws25/src/pure_pursuit/racelines/Raceline_outside.csv"
      min_lookahead: 1.0
      max_lookahead: 3.0
      lookahead_ratio: 8.0
      K_p: 0.2
      velocity_percentage: 0.5

waypoint_visualiser_node:
  ros__parameters:
    waypoints_path: "/home/f1tenth/f1tenth_auto_blocking/lab_ws25/src/pure_pursuit/racelines/Raceline_middle.csv"
